sect1:
  prop1: ${sect1.prop11}/${sect1.prop12}
  prop2: ${sect1.prop12}
  prop3: ${sect1.prop13}
sect2:
  prop1: ${sect2.prop21}
  prop2: ${sect2.prop22}
  prop3: ${sect2.prop23}
sect3:
  prop1: ${sect3.prop31}
  prop2: ${sect3.prop32}
  prop3: ${sect3.prop33}
custom:
  prop1: ${custom.propC1}
  prop2: ${custom.propC2}
  prop3: ${custom.propC3}